2024-04-17 01:43:56,496 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 01:44:03,346 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 01:44:04,076 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 01:44:23,903 INFO: 유저 ID: <User 123@123.com> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-17 01:44:23,906 INFO: Model: <Model 1>, Dataset: <Dataset 2> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-17 01:44:23,935 INFO: 프로젝트 생성 성공: Project ID 1 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-17 01:44:24,041 INFO: 수정된 파일: {'id': 1, 'model': 1, 'dataset': 2, 'hyperparameters': {'learningRate': 0.1, 'batchSize': 32, 'epochs': 10, 'optimizer': 1, 'lossFunction': 1}, 'nodes': ['13.124.158.135', '15.165.105.49'], 'status': [['16', '0.1987288135569587', '0.1875', '48267595776', '215189311488', '19', '9.607', '0', None, '66583072768', '233946071040', 'Tesla T4,1'], ['1', '2.125423728819875', '2', '51346374656', '111302340608', '31', '9.364', '0', None, '67422306304', '130922102784', 'Tesla T4,1'], ['16', '0.6544491525414364', '2.0625', '46589198336', '214118027264', '23', '11.978', '0', None, '66583064576', '233946071040', 'Tesla T4,1'], ['16', '0.016525423733104727', '0', '58713448448', '123309592576', None, None, None, None, '66209673216', '130911944704', None]]} [in D:\develop\vue-flask-dashboard\backend\app\routes.py:116]
2024-04-17 01:46:11,326 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4952AC1A0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:327]
2024-04-17 01:46:13,198 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4952A3950>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:327]
2024-04-17 01:46:16,215 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4952ACEC0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:327]
2024-04-17 01:46:19,233 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4952A1E20>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:327]
2024-04-17 01:46:22,226 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4952AF380>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:327]
2024-04-17 01:46:25,219 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4952AC470>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:327]
2024-04-17 01:47:15,908 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 01:47:22,804 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 01:47:23,493 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 01:47:37,196 INFO: 유저 ID: <User 123@123.com> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-17 01:47:37,199 INFO: Model: <Model 1>, Dataset: <Dataset 2> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-17 01:47:37,219 INFO: 프로젝트 생성 성공: Project ID 1 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-17 01:47:37,329 INFO: 수정된 파일: {'id': 1, 'model': 1, 'dataset': 2, 'hyperparameters': {'learningRate': 0.1, 'batchSize': 32, 'epochs': 10, 'optimizer': 1, 'lossFunction': 1}, 'nodes': ['13.124.158.135', '15.165.105.49'], 'status': [['16', '0.5207627118635205', '1.125', '48278396928', '215188611072', '21', '25.977', '5', None, '66583072768', '233946071040', 'Tesla T4,1'], ['1', '14.70169491527239', '43', '51655262208', '111302004736', '32', '9.364', '0', None, '67422306304', '130922102784', 'Tesla T4,1'], ['16', '0.7828389830498717', '0.5', '46579355648', '214116622336', '23', '12.18', '0', None, '66583064576', '233946071040', 'Tesla T4,1'], ['16', '0.1895775564563884', '0.5', '58716622848', '123309592576', None, None, None, None, '66209673216', '130911944704', None]]} [in D:\develop\vue-flask-dashboard\backend\app\routes.py:116]
2024-04-17 01:49:02,392 INFO: 유저 ID: <User 123@123.com> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-17 01:49:02,393 INFO: Model: <Model 1>, Dataset: <Dataset 1> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-17 01:49:02,411 INFO: 프로젝트 생성 성공: Project ID 2 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-17 01:49:02,517 INFO: 수정된 파일: {'id': 2, 'model': 1, 'dataset': 1, 'hyperparameters': {'learningRate': 0.1, 'batchSize': 32, 'epochs': 10, 'optimizer': 1, 'lossFunction': 1}, 'nodes': ['13.124.158.135', '43.203.73.249'], 'status': [['16', '0.5247881355923911', '0.25', '48269221888', '215188299776', '19', '9.118', '0', None, '66583072768', '233946071040', 'Tesla T4,1'], ['1', '20.786440677968475', '17', '51180183552', '111301857280', '31', '11.35', '0', None, '67422306304', '130922102784', 'Tesla T4,1'], ['16', '0.9313559322001397', '0.75', '46578409472', '214116012032', '24', '9.523', '0', None, '66583064576', '233946071040', 'Tesla T4,1'], ['16', '2.767608355192186', '2.375', '58637885440', '123309588480', None, None, None, None, '66209673216', '130911944704', None]]} [in D:\develop\vue-flask-dashboard\backend\app\routes.py:116]
2024-04-17 01:49:48,161 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 01:49:55,852 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 01:49:56,566 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 01:51:02,646 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 01:51:13,466 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 01:51:14,157 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 01:52:21,016 INFO: 유저 ID: <User 123@123.com> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-17 01:52:21,018 INFO: Model: <Model 2>, Dataset: <Dataset 2> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-17 01:52:21,038 INFO: 프로젝트 생성 성공: Project ID 1 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-17 01:52:21,143 INFO: 수정된 파일: {'id': 1, 'model': 2, 'dataset': 2, 'hyperparameters': {'learningRate': 0.1, 'batchSize': 32, 'epochs': 30, 'optimizer': 1, 'lossFunction': 1}, 'nodes': ['13.124.158.135', '43.203.73.249'], 'status': [['16', '0.5036016949156341', '0', '48272789504', '215187562496', '19', '10.787', '0', None, '66583072768', '233946071040', 'Tesla T4,1'], ['1', '14.233898305081594', '0', '51409641472', '111301500928', '31', '9.264', '0', None, '67422306304', '130922102784', 'Tesla T4,1'], ['16', '0.8747881355915421', '0.0625', '46567878656', '214114607104', '23', '9.326', '0', None, '66583064576', '233946071040', 'Tesla T4,1'], ['16', '2.6822275781158034', '0.0625', '58717728768', '123309588480', None, None, None, None, '66209673216', '130911944704', None]]} [in D:\develop\vue-flask-dashboard\backend\app\routes.py:116]
2024-04-17 01:53:44,901 INFO: 유저 ID: <User 123@123.com> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-17 01:53:44,902 INFO: Model: <Model 2>, Dataset: <Dataset 1> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-17 01:53:44,921 INFO: 프로젝트 생성 성공: Project ID 2 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-17 01:55:06,527 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000175E9B92BA0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:327]
2024-04-17 02:00:31,747 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
