2024-04-16 20:29:58,697 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-16 20:30:21,391 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-16 20:30:22,093 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-16 21:01:45,160 INFO: 유저 ID: <User 123@123.com> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-16 21:01:45,163 INFO: Model: <Model 1>, Dataset: <Dataset 1> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-16 21:01:45,176 INFO: 프로젝트 생성 성공: Project ID 1 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-16 21:01:45,279 INFO: 수정된 파일: {'id': 1, 'model': 1, 'dataset': 1, 'hyperparameters': {}, 'nodes': ['13.124.158.135', '15.165.105.49'], 'status': [['16', '0.18411016949158032', '0.375', '48111751168', '215261339648', '27', '25.85', '0', None, '66583072768', '233946071040', 'Tesla T4,1'], ['1', '2.1661016949199974', '0', '51768811520', '111395241984', '31', '9.264', '0', None, '67422306304', '130922102784', 'Tesla T4,1'], ['16', '0.26313559322245217', '0.125', '46527807488', '214230777856', '29', '25.613', '0', None, '66583064576', '233946071040', 'Tesla T4,1'], ['16', '0.015466101693295542', '0', '58720919552', '123358928896', None, None, None, None, '66209673216', '130911944704', None]]} [in D:\develop\vue-flask-dashboard\backend\app\routes.py:116]
2024-04-16 22:18:35,463 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAEBD6D0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:18:38,440 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAEBF7D0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:18:41,446 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAEBCB60>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:18:44,444 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAE9A480>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:18:47,943 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CADEB2C0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:18:50,451 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAE9A780>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:18:53,449 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAEBD010>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:18:56,437 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAEBE990>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:18:59,462 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAE9A9F0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:19:02,451 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAEADDF0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:19:05,443 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAEAEB10>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:19:09,116 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CADE87D0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:19:12,138 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAEBD280>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:19:15,127 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAEBCFE0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:19:18,121 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAE9B200>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:19:21,127 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAEAEA80>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 22:19:24,125 ERROR: Error fetching project 2 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8CAEBEBD0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-16 23:23:17,423 INFO: 유저 ID: <User 123@123.com> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-16 23:23:17,425 INFO: Model: <Model 1>, Dataset: <Dataset 1> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-16 23:23:17,443 INFO: 프로젝트 생성 성공: Project ID 2 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
